# Generated by Django 4.1.7 on 2023-03-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodstand",
            name="business_name",
            field=models.CharField(default="Nadia Business", max_length=100),
            preserve_default=False,
        ),
    ]
